### ISSUE TITLE
simple page not found

### ISSUE THREAD

**Issue by asharma567** [knockrentals/walkscore#1]
https://github.com/knockrentals/walkscore/blob/master/walkscore-api-binding/example.py

**Comment by jayzeng** [comment]
Good catch, it is moved to https://github.com/knockrentals/walkscore/blob/master/example/example.py, I will update the README

**Comment by jayzeng** [comment]
Fixed in https://github.com/knockrentals/walkscore/commit/1e53d016fc1fa83410df634aa3e7b2a3fec8b0f3
