### ISSUE TITLE
conflict with API and website

### ISSUE THREAD

**Issue by asharma567** [knockrentals/walkscore#2]
('5021 Academy Ln', 33.34, -86.958) yields 0 through API and 19 on website. Was just curious if you knew why.

**Comment by jayzeng** [comment]
If I were to guess, your address looks incomplete (missing city, state and/or zip) and walkscore isn't smart enough about that. 

I don't quite understand why they will require lat/lng plus address, which seems redundant in my opinion.

**Comment by asharma567** [comment]
Yeah, that doesn't make sense. In any case, just thought I should check
with you first before digging deeper.

Thanks again,
- Ajay
ᐧ

On Thu, Jun 18, 2015 at 10:53 AM, Jay Zeng <notifications@github.com> wrote:

> If I were to guess, your address looks incomplete (missing city, state
> and/or zip) and walkscore isn't smart enough about that.
>
> I don't quite understand why they will require lat/lng plus address, which
> seems redundant in my opinion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knockrentals/walkscore/issues/2#issuecomment-113236255>
> .
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by jayzeng** [comment]
Sure thing, let me know if you have any other questions, happy to help.

**Comment by jayzeng** [comment]
Closing this issue, please re-open if you have more questions.
