### ISSUE TITLE
Transit Score?

### ISSUE THREAD

**Issue by stefancoe** [knockrentals/walkscore#4]
Very happy to find this! Any plans to do the same for Transit Score? Thanks!

**Comment by jayzeng** [comment]
@stefancoe glad you like it! I didn't there is Transit score and I am motivated to add support for that, do you have specific use case or endpoints that I can start with?

**Comment by stefancoe** [comment]
Thanks for the prompt response! I work for a regional planning organization and we are thinking about using these scores to help characterize places such as regional centers. So it would be used exactly the same way one would use walk score. I imagine any lat/long in a city with transit would work for testing purposes? 
https://www.walkscore.com/professional/public-transit-api.php

**Comment by jayzeng** [comment]
Got it, will mock something up this week and let you know when it is ready

**Comment by stefancoe** [comment]
Thanks!

**Comment by jayzeng** [comment]
@stefancoe didn't find time until now, https://github.com/knockrentals/walkscore/pull/5/files should do the trick. I will do some testing and push to master and pypi soon, let me know if you have any comment.

**Comment by jayzeng** [comment]
@stefancoe code is done and pushed to pypi, you may pick it up with pip install ```walkscore-api-binding --upgrade```

Example code is available at: https://github.com/knockrentals/walkscore/blob/master/example/transitscore.py

Let me know if you have any comment/feedback.

**Comment by stefancoe** [comment]
Thanks so much!
